// let first = document.getElementById("first")
// let a = first.getAttribute("class")
// console.log(a)
// console.log(first.hasAttribute("class"))
// console.log(first.hasAttribute("style"))
// console.log(  first.setAttribute("hidden","tru"))
// first.setAttribute("fall","tru")
// first.removeAttribute("class")
//  console.log(first.Attribute)
  console.log(first.dataset)
  console.log(first.dataset.game)
  console.log(first.dataset.player)
  